### ISSUE TITLE
Randomly closing with no codes generated

### ISSUE THREAD

**Issue by pythonishard** [therealtear/discord-nitro-generator#1]
Generator will close by itself leaving codes.json empty

**Comment by therealtear** [comment]
> Generator will close by itself leaving codes.json empty

It shouldn’t be closing itself is there an error message?

**Comment by marcel9164** [comment]
no there's no error message

**Comment by therealtear** [comment]
> no there's no error message

Then there isn’t really a problem lol did u follow all the steps in the read me?

**Comment by Redomic** [comment]
Same here. Seems to close without any errors after 2-3 minutes.

**Comment by therealtear** [comment]
> Same here. Seems to close without any errors after 2-3 minutes.

Might be because you ran out of proxies if u could explain ur situation in a bit more detail it would be helpful such as what ur computer specs are and what kind of internet u have

**Comment by Redomic** [comment]
Seems to run completely fine on Linux but shuts down after a while on Windows 10, might again be the proxy issue but there's no Error message so can't tell. I have a pretty good internet connection running on ethernet. Apart from that, might just be windows being windows

**Comment by therealtear** [comment]
> Seems to run completely fine on Linux but shuts down after a while on Windows 10, might again be the proxy issue but there's no Error message so can't tell. I have a pretty good internet connection running on ethernet. Apart from that, might just be windows being windows

Tbh I havnt run this version of the gen (using request vs fetch) on windows for a few months lol even then I was using a vm but it should work fine on Mac and any version of Linux really I’ll look into this more tomorrow as to why windows users are having this issue

**Comment by Johna-3212** [comment]
There's an error with request. If you run it in console by `node .` you'll notice.
