### ISSUE TITLE
error

### ISSUE THREAD

**Issue by adrianlp03** [therealtear/discord-nitro-generator#10]
Cannot find module 'colors'
Require stack:
- C:\Users\adria\Downloads\discord-nitro-generator-main\app.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\adria\Downloads\discord-nitro-generator-main\app.js:4:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\adria\\Downloads\\discord-nitro-generator-main\\app.js'←[39m
  ]
}
ALGUNA SOLUCION?

**Comment by therealtear** [comment]
> Cannot find module 'colors'
> Require stack:
> 
> * C:\Users\adria\Downloads\discord-nitro-generator-main\app.js
>   ←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
>   ←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
>   ←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
>   at Object. (C:\Users\adria\Downloads\discord-nitro-generator-main\app.js:4:16)
>   ←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
>   ←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
>   ←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
>   ←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
>   code: ←[32m'MODULE_NOT_FOUND'←[39m,
>   requireStack: [
>   ←[32m'C:\Users\adria\Downloads\discord-nitro-generator-main\app.js'←[39m
>   ]
>   }
>   ALGUNA SOLUCION?

Read the instructions you forgot to install the packages with npm i
