### ISSUE TITLE
Don't work 

### ISSUE THREAD

**Issue by Logipek** [therealtear/discord-nitro-generator#13]
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack:
- C:\Users\\Desktop\discord-nitro-generator-main\app.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
    at Object.<anonymous> (C:\Users\\Desktop\discord-nitro-generator-main\app.js:4:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [ ←[32m'C:\\Users\\\Desktop\\discord-nitro-generator-main\\app.js'←[39m ]
}

**Comment by therealtear** [comment]
> internal/modules/cjs/loader.js:883
> throw err;
> ^
> 
> Error: Cannot find module 'colors'
> Require stack:
> 
> * C:\Users\Desktop\discord-nitro-generator-main\app.js
>   ←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:725:27)←[39m
>   ←[90m    at Module.require (internal/modules/cjs/loader.js:952:19)←[39m
>   ←[90m    at require (internal/modules/cjs/helpers.js:88:18)←[39m
>   at Object. (C:\Users\Desktop\discord-nitro-generator-main\app.js:4:16)
>   ←[90m    at Module._compile (internal/modules/cjs/loader.js:1063:30)←[39m
>   ←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)←[39m
>   ←[90m    at Module.load (internal/modules/cjs/loader.js:928:32)←[39m
>   ←[90m    at Function.Module._load (internal/modules/cjs/loader.js:769:14)←[39m
>   ←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)←[39m {
>   code: ←[32m'MODULE_NOT_FOUND'←[39m,
>   requireStack: [ ←[32m'C:\Users\\Desktop\discord-nitro-generator-main\app.js'←[39m ]
>   }

Holy fuck your stupid I’m not even gonna tell you how to fix it because I’ve explained 20 times in other issues already
