### ISSUE TITLE
Windows cannot find .bat

### ISSUE THREAD

**Issue by azorkai** [therealtear/discord-nitro-generator#14]
![image](https://user-images.githubusercontent.com/59281149/104058855-6d7aa380-5205-11eb-82b3-a2fd48b2ce04.png)

**Comment by therealtear** [comment]
Why is the nitro gen in system 32? Try moving it to your desktop

**Comment by azorkai** [comment]
it is not in system 32...

**Comment by therealtear** [comment]
![Uploading EA9B4C55-E5FE-48E2-BFAC-A33D550FD566.jpeg…]()

**Comment by azorkai** [comment]
F:\Discordnitrogenerator-main\Discordnitrogenerator-main\Discord nitro generator\Nitrx-master\discord-nitro-generator-main\discord-nitro-generator-main

**Comment by therealtear** [comment]
> F:\Discordnitrogenerator-main\Discordnitrogenerator-main\Discord nitro generator\Nitrx-master\discord-nitro-generator-main\discord-nitro-generator-main

Idk man try redownloading it and starting from the begging or try following the Mac/linux steps
