### ISSUE TITLE
Auto proxy scrape

### ISSUE THREAD

**Issue by DarkGD123** [therealtear/discord-nitro-generator#15]
Insted of manually getting all the proxies by yourself, the script should scrape them then save it on ```proxies.txt```

**Comment by DarkGD123** [comment]
Also nodejs gives me these errors
```npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported```

**Comment by therealtear** [comment]
> Insted of manually getting all the proxies by yourself, the script should scrape them then save it on `proxies.txt`

Check the second branch I already added that when it hits 0 left lol

**Comment by therealtear** [comment]
> Also nodejs gives me these errors
> `npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142 npm WARN deprecated har-validator@5.1.5: this library is no longer supported`

That’s not an error

**Comment by DarkGD123** [comment]
well how do i avoid this thing

**Comment by therealtear** [comment]
There’s literally no problem :/

**Comment by DarkGD123** [comment]
yeah i know but when i execute the file the script says `no module named request`

**Comment by therealtear** [comment]
> yeah i know but when i execute the file the script says `Cant find module "request"`

npm i request

**Comment by DarkGD123** [comment]
![_20210110_103048](https://user-images.githubusercontent.com/42462384/104112924-5f28a680-532f-11eb-9b41-986e27489503.JPG)

**Comment by therealtear** [comment]
That is strange try changing the package.json file and change the version of request to 0.2

**Comment by DarkGD123** [comment]
It cant find the version of request 0.2
Well i checked every version in https://www.npmjs.com/package/request

All of the versions are deprecated

**Comment by therealtear** [comment]
> It cant find the version of request 0.2
> Well i checked every version in https://www.npmjs.com/package/request
> 
> All of the versions are deprecated

Wtf that’s so weird it’s still working fine for me idk what the problem is tbh just because a module is depreciated doesn’t mean it doesn’t work but that’s really weird

**Comment by DarkGD123** [comment]
ok everything is working i had to use a random version of request

**Comment by therealtear** [comment]
> ok everything is working i had to use a random version of request

Bruh
