### ISSUE TITLE
Can i run this on repl.it

### ISSUE THREAD

**Issue by ctctk9** [therealtear/discord-nitro-generator#2]
I want it to run on repl.it, will it work?

**Comment by therealtear** [comment]
Yes you can :) I’ll be updating the readme tomorrow thanks for reminding me I completely forgot!

**Comment by ctctk9** [comment]
tried but it doesn't work on repl.it

**Comment by therealtear** [comment]
> tried but it doesn't work on repl.it because i dont know my repl.it ip to uptimerobot it

you would need to create a webserver in order to do so ill update the code today and include better instructions

**Comment by ctctk9** [comment]
Thank you :) I checked for about 4 about but no working code. Please update it.

**Comment by therealtear** [comment]
> Thank you :) I checked for about 4h but no working code. Please update it.

Everything works completely fine...

**Comment by ctctk9** [comment]
so I'm unlucky xD

**Comment by therealtear** [comment]
> so I'm unlucky xD

Correct

**Comment by ctctk9** [comment]
But have you ever got hit yet?

**Comment by therealtear** [comment]
> But have you ever hit nitro yet?

Yes multiple I even got 2 year long boost nitro codes

**Comment by ctctk9** [comment]
wow xD
