### ISSUE TITLE
Destroy error

### ISSUE THREAD

**Issue by Redomic** [therealtear/discord-nitro-generator#2]
Got an error after running for 3 minutes

```
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:111:27)
Emitted 'error' event at:
    at emitErrorNT (internal/streams/destroy.js:91:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
    at process._tickCallback (internal/process/next_tick.js:63:19)

```

**Comment by therealtear** [comment]
That means u ran out of proxies lol add more and try again I’ll add better error support tomorrow if I have time

**Comment by Johna-3212** [comment]
You can just loop over proxies

**Comment by HZ-0Z3R0** [comment]
I think proxies loop by default? I fixed a similar error by deleting an extra line at the end of proxies.txt. @Redomic

**Comment by Johna-3212** [comment]
They don't loop

**Comment by HZ-0Z3R0** [comment]
I added only about 20 proxies and was able to run forever as far as I know, occasionally the proxies show as invalid and switch, but I think it looped because Discord has a 5/5 rate limit.

**Comment by therealtear** [comment]
> I added only about 20 proxies and was able to run forever as far as I know, occasionally the proxies show as invalid and switch, but I think it looped because Discord has a 5/5 rate limit.

I will be completely remaking this project from scratch soon when I have time but all 3 of my computers are sadly not working at this time. Expect to see a proxy using option with proper looping and an actual proxy scrapper built in as well as a non proxy using option that respects discord’s rate limiting without the hassle of having non working proxies

**Comment by Johna-3212** [comment]
I am sure they don't cause we are increasing proxyline and once it reaches last, it doesn't go to the first proxy

**Comment by Johna-3212** [comment]
I made proxy scraper and looping method I'll share soon

**Comment by therealtear** [comment]
> I am sure they don't cause we are increasing proxyline and once it reaches last, it doesn't go to the first proxy

It doesn’t loop you are correct I will make it loop soon and explain why I chose to build it this way in the readme or on an official issues thread of some sort just been hella busy lately I havnt forgot about you guys lol also mobile is proving more difficult then anticipated

**Comment by Johna-3212** [comment]
You can check my latest pr

**Comment by therealtear** [comment]
> You can check my latest pr

Sure thing

**Comment by therealtear** [comment]
> You can check my latest pr

I’ll probably also pull off HMA as well

**Comment by Johna-3212** [comment]
What's hma?

**Comment by therealtear** [comment]
> What's hma?

Hide my ass I also already have a scrapper n checker but may as well use this for now

**Comment by Johna-3212** [comment]
Just asking, can you add me on discord please Johna#1708

**Comment by Johna-3212** [comment]
Want to ask something

**Comment by therealtear** [comment]
> Just asking, can you add me on discord please Johna#1708

Sure thing
