### ISSUE TITLE
Pressing N doesn't stop the generator

### ISSUE THREAD

**Issue by tuckMCWizard** [therealtear/discord-nitro-generator#23]
Title says it, not sure why, it just doesn't do anything when I press N to stop it, and I have to close the terminal manually. 

Using macOS 10.15.7 and node.js 14.15.4

**Comment by therealtear** [comment]
yea it doesn't really work anymore lol but ill fix this in a future update thank you for listing your current device being used as well as your version of node that is very helpful for almost all issues
