### ISSUE TITLE
Doesn't notify about ratelimits

### ISSUE THREAD

**Issue by maalos** [therealtear/discord-nitro-generator#26]
from what i've seen the json code on the api's page doesnt really provide a code when i'm being ratelimited and i got ratelimited for 12hrs str8 lol now i have a 600000 timeout that doesnt go down even tho its not running, yes, i didnt use proxies cause i was unsure, either way something is wrong, if you want i could pull it and fix it

**Comment by maalos** [comment]
![Screenshot_2021-01-17-13-16-13-06.jpg](https://user-images.githubusercontent.com/54448857/104842116-ded1ea80-58c6-11eb-902f-95c9536b2888.jpg) are the codes right? when the page responds with 200 it should stop but i feel like... nvm there are ppl that got nitro so imma just leave that there

**Comment by maalos** [comment]
and on every open terminal window this is spamming ![Screenshot_2021-01-17-17-49-48-89.jpg](https://user-images.githubusercontent.com/54448857/104849885-7e55a400-58ec-11eb-9078-61f583ae7002.jpg)

**Comment by therealtear** [comment]
> and on every open terminal window this is spamming ![Screenshot_2021-01-17-17-49-48-89.jpg](https://user-images.githubusercontent.com/54448857/104849885-7e55a400-58ec-11eb-9078-61f583ae7002.jpg)

Because u had so many instances running...
