### ISSUE TITLE
How much instances of the program is recommended?

### ISSUE THREAD

**Issue by maalos** [therealtear/discord-nitro-generator#27]
As in title. Rn im running 24 proxied for 10hrs str8 and didnt get anything, is 1 enough to get anything in under 24hrs?

**Comment by maalos** [comment]
felt like its not enough so i turned on 32

**Comment by maalos** [comment]
but on phone not connected to my wifi with seperate fresh proxies: ![Screenshot_2021-01-17-21-13-31-29.jpg](https://user-images.githubusercontent.com/54448857/104854794-0c3f8800-5909-11eb-89eb-61ad7b6bf659.jpg)![Screenshot_2021-01-17-21-14-08-16.jpg](https://user-images.githubusercontent.com/54448857/104854797-0fd30f00-5909-11eb-85a4-c7b054fda450.jpg)

**Comment by therealtear** [comment]
jfc only run 1 and no more
