### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by ctctk9** [therealtear/discord-nitro-generator#28]
Getting "No proxies detected now scrapping..." when using domain proxies, for exp: usa.rotating.proxyrack.net

**Comment by Kweeper** [comment]
bruh goto proxiyscrape.com/ and get http proxies and put then all in the proxiy file ez

**Comment by ctctk9** [comment]
bruh prosc proxies is sh**

**Comment by therealtear** [comment]
> bruh proxsc proxies is sh**

( ͡° ͜ʖ ͡°) then find one that works not my problem you differed from the norm

**Comment by ctctk9** [comment]
> > bruh proxsc proxies is sh**
> 
> ( ͡° ͜ʖ ͡°) then find one that works not my problem you differed from the norm

then how can it work with doamain proxies (ˉ﹃ˉ)

**Comment by therealtear** [comment]
> > > bruh proxsc proxies is sh**
> > 
> > 
> > ( ͡° ͜ʖ ͡°) then find one that works not my problem you differed from the norm
> 
> then how can it work with doamain proxies (ˉ﹃ˉ)

Find http protocol proxies and any should work just fine but it will still scrape for the loop off of proxyscrape I’ll add more choices soon
