### ISSUE TITLE
Another proxy problem

### ISSUE THREAD

**Issue by AuspiciousFaxMachine** [therealtear/discord-nitro-generator#29]
I have copy and pasted the correct proxy files from the website given in the instructions. However, after generating Nitro codes for a while, the Terminal will only repeat the invalid proxy message.
![Screen Shot 2021-01-24 at 9 12 39 PM](https://user-images.githubusercontent.com/74377400/105653091-e6762e00-5e88-11eb-8ea5-8cd67c059a76.png)

**Comment by maalos** [comment]
same here, 2 instances running, 1 proxied and 1 non proxied

**Comment by therealtear** [comment]
Proxyscrape api must be having issues nothing I can do I’m sorry gonna leave this up for a few days in case anyone else checks here before spamming my dms begging for more codes

**Comment by AuspiciousFaxMachine** [comment]
It's alright! Thanks anyways.

**Comment by therealtear** [comment]
> It's alright! Thanks anyways.

Yea np sorry for the late reply
