### ISSUE TITLE
Invalid proxy switching now

### ISSUE THREAD

**Issue by 685** [therealtear/discord-nitro-generator#3]
After 50 tries it becomes slow and then just always shows "invalid proxy switching now"
Is there a way to loop the proxy list?

**Comment by therealtear** [comment]
> After 50 tries it becomes slow and then just always shows "invalid proxy switching now"
> Is there a way to loop the proxy list?

I will be completely remaking this project from scratch soon when I have time but all 3 of my computers are sadly not working at this time. Expect to see a proxy using option with proper looping and an actual proxy scrapper built in as well as a non proxy using option that respects discord’s rate limiting without the hassle of having non working proxies
