### ISSUE TITLE
Announcement 

### ISSUE THREAD

**Issue by therealtear** [therealtear/discord-nitro-generator#31]
I’ll be adding some more features this upcoming week because I have a lot more time also all my discord accounts got disabled because of another issue so I’ll be making a new one shortly as well as a support server of some kind 
On a side note my accs got disabled for a raiding thing nothing to do with the generator also I had 23 months of nitro on my main in case anyone was wondering at the time of the disable

**Comment by ctctk9** [comment]
nicesu bro
