### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Raulaca1** [therealtear/discord-nitro-generator#33]
Hi I Hello, I have been running for 7 hours 9 generators and it still has not given me a functional code how long does it take to give me one!? :(

**Comment by therealtear** [comment]
> Hi I Hello, I have been running for 7 hours 9 generators and it still has not given me a functional code how long does it take to give me one!? :(

If you read any single error thread at all you would notice that running more than 1 instance of the generator at a time just straight up breaks it and it won’t work

**Comment by Raulaca1** [comment]
so I just have to have a generator no more?

**Comment by Raulaca1** [comment]
can i have more than one active generator?

**Comment by therealtear** [comment]
> so I just have to have a generator no more?

Yes

**Comment by therealtear** [comment]
> can i have more than one active generator?

No

**Comment by Raulaca1** [comment]
Ok thanks

**Comment by therealtear** [comment]
> Ok thanks

Sorry for late reply but your welcome :) if you need more help feel free to join the discord server

https://discord.gg/aptF5UjZZf
