### ISSUE TITLE
Discord server

### ISSUE THREAD

**Issue by therealtear** [therealtear/discord-nitro-generator#34]
https://discord.gg/aptF5UjZZf

I finally got a new account and made the server there will be a lot of changes to it as time goes on but this is the official server that you can get support for any of my projects or if you want to talk to other like-minded individuals and work on other stuff together

**Comment by vadimka04** [comment]
lLnk not work

**Comment by therealtear** [comment]
> Link not work

Had to cancel it cause people we didn’t want got in just add me tear#9998 I’ll send a invite
