### ISSUE TITLE
proxy question

### ISSUE THREAD

**Issue by ctctk9** [therealtear/discord-nitro-generator#35]
there is something still wrong 🤣🤣🤣🤣🤣
as i can see there is "No proxies detected now scrapping..." when no proxies but when i run it doesnt show that and still checking like crazy 🥶

**Comment by therealtear** [comment]
> there is something still wrong 🤣🤣🤣🤣🤣
> as i can see there is "No proxies detected now scrapping..." when no proxies but when i run it doesnt show that and still checking like crazy 🥶

Yea I noticed that too lol I was unsure at first but read line reads all the proxies beforehand so if you remove them it’ll still check until it runs out and the “now scraping” text prompt was broken before lol should be fixed now like it just showed every single proxies change even when nothing happened
