### ISSUE TITLE
Antivirus detecting trojan

### ISSUE THREAD

**Issue by dxnnyzz** [therealtear/discord-nitro-generator#38]
Hi, while running the Nitro Gen, my antivirus would sometimes notify that some IP address is a trojan and blocking it. I don't know whether it's something with the proxy lists or.. I would like to ask if I should disable my antivirus or not?
Thanks.

**Comment by dxnnyzz** [comment]
I'm using Malwarebytes by the way if you were wondering.

**Comment by therealtear** [comment]
> Hi, while running the Nitro Gen, my antivirus would sometimes notify that some IP address is a trojan and blocking it. I don't know whether it's something with the proxy lists or.. I would like to ask if I should disable my antivirus or not?
> Thanks.

That is the most retarded shit I’ve ever heard in my entire fucking life please hang yourself before you reproduce
