### ISSUE TITLE
Antivirus problem

### ISSUE THREAD

**Issue by VoidDave** [therealtear/discord-nitro-generator#39]
![image](https://user-images.githubusercontent.com/62336875/107742308-19387700-6d0f-11eb-8aff-35c41e1f04fe.png)
My antivirus eset saing url block for discord and that ip. What should o do ?
PS. it only apper when program is on

**Comment by therealtear** [comment]
> ![image](https://user-images.githubusercontent.com/62336875/107742308-19387700-6d0f-11eb-8aff-35c41e1f04fe.png)
> My antivirus eset saing url block for discord and that ip. What should o do ?
> PS. it only apper when program is on

Wtf proxies suck ig either just turn off ur antivirus while running the program or get better proxies
