### ISSUE TITLE
waaaa waaa gu gu ga ga

### ISSUE THREAD

**Issue by lukeacat** [therealtear/discord-nitro-generator#41]
im gonna pissy in my panty

ive been running this shit (1 proxied 1 not proxied) for 12h
already and i havent got a nitro ?? 

it no worky

**Comment by therealtear** [comment]
> im gonna pissy in my panty
> 
> ive been running this shit (1 proxied 1 not proxied) for 12h
> already and i havent got a nitro ??
> 
> it no worky

Not my problem fuck off
