### ISSUE TITLE
Program automatically closes and got windows defender alert.

### ISSUE THREAD

**Issue by Realogdripa** [therealtear/discord-nitro-generator#44]
Hey there! Please read this thoroughly. So, I tried this out and wanted to start the code (i have done the previous steps). I clicked on start.bat. But the thing is as soon as it opens, after about 10 milliseconds it automatically closes. I have node.js already installed on my pc. My second concern is that is this safe? I got a windows defender alert when I clicked on start.bat. But I ran it anyways. Still a bit worried tho. Please respond as soon as possible

**Comment by therealtear** [comment]
Why the fuck would your windows anti defender go off there is literally nothing malicious about this you prolly downloaded a different version someone stole off a sketchy discord server and got ratted
