### ISSUE TITLE
No code in over 72 hours, discord server link invalid

### ISSUE THREAD

**Issue by SushiClicker** [therealtear/discord-nitro-generator#46]
I've been running the generator in a repl.it with always on enabled. I've been running it for over 3 days, and haven't gotten a single code. I don't have any errors. Is there anything wrong, or do I just need to wait longers? Also, the discord server link you've provided in other issues isn't working. Can you provide a never expiring link?

**Comment by SushiClicker** [comment]
I'm running the code for a regular generator inside of a repl.it. I'm not using the repl.it version with webhooks.

**Comment by lukeacat** [comment]
Same, I've been running this shit for around 5 days, still nothing.

**Comment by therealtear** [comment]
> I'm running the code for a regular generator inside of a repl.it. I'm not using the repl.it version with webhooks.

There’s your problem ^^^^ lmfao
