### ISSUE TITLE
does it work

### ISSUE THREAD

**Issue by matsan1122** [therealtear/discord-nitro-generator#57]
i am running the generator now but i don't know if it works.do you really get nitro and what nitro. classic or another.

**Comment by emavergas** [comment]
> i am running the generator now but i don't know if it works.do you really get nitro and what nitro. classic or another.

No it doesn't

**Comment by matsan1122** [comment]
why not?

**Comment by Revelation420** [comment]
Actually It Works

**Comment by therealtear** [comment]
it works fine
