### ISSUE TITLE
?

### ISSUE THREAD

**Issue by matsan1122** [therealtear/discord-nitro-generator#58]
does anyone have got nitro from this? i am very curious. my discord is:MatSan112#9485

**Comment by matsan1122** [comment]
and if someone still has a classic nitro. i want it really bad so if you have many can you maybe give 1 to me

**Comment by therealtear** [comment]
> and if someone still has a classic nitro. i want it really bad so if you have many can you maybe give 1 to me

shut the fuck up beggar
