### ISSUE TITLE
Discord Webhook Report

### ISSUE THREAD

**Issue by 7yf** [therealtear/discord-nitro-generator#59]
You could add an option to report working nitro codes to a discord webhook. Not really needed but would be cool to have.

**Comment by therealtear** [comment]
it would get rate limited and be super backed up and could get the server banned

**Comment by therealtear** [comment]
> You could add an option to report working nitro codes to a discord webhook. Not really needed but would be cool to have.

if you really want it added copy the webhook sender from the replit branch
