### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by iQAIRHUB** [therealtear/discord-nitro-generator#6]
I keep getting this error:

 "An error occurred:
SyntaxError: Unexpected token e in JSON at position 0"

it appears randomly

**Comment by therealtear** [comment]
> I keep getting this error:
> 
> "An error occurred:
> SyntaxError: Unexpected token e in JSON at position 0"
> 
> it appears randomly

That means you have something else in the proxies file or codes file that isn’t either a proxy or a code just delete it and it should go away

**Comment by therealtear** [comment]
> I keep getting this error:
> 
> "An error occurred:
> SyntaxError: Unexpected token e in JSON at position 0"
> 
> it appears randomly

That means you have something else in the proxies file or codes file that isn’t either a proxy or a code just delete it and it should go away

**Comment by iQAIRHUB** [comment]
> > I keep getting this error:
> > "An error occurred:
> > SyntaxError: Unexpected token e in JSON at position 0"
> > it appears randomly
> 
> That means you have something else in the proxies file or codes file that isn’t either a proxy or a code just delete it and it should go away
If it finds a code it will go into codes.json right?

**Comment by therealtear** [comment]
> > I keep getting this error:
> > "An error occurred:
> > SyntaxError: Unexpected token e in JSON at position 0"
> > it appears randomly
> 
> That means you have something else in the proxies file or codes file that isn’t either a proxy or a code just delete it and it should go away
> If it finds a code it will go into codes.json right?

Yes
